# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: myFinalPool

variables:
  system.debug: true
  python.version: '3.9'
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: 'myServiceConnection'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: 'test'
  #Resource Group Name
  rgname: 'endrias2024_rg_354888' 
  #Storage Name
  storename: 'mystoragefinalproj' 
  #App Name
  appname: 'endriasApplication-AppService'
  backend_key: 'test.terraform.tfstate'
  storage_account_key: 'SIX4qMsGiDSN40qEZ+YFZm8MZB0EDmLLz3YGlQkgrG/u92UAJCLhgdqrvVK6qqAWrM6OASsFCeXZ+ASt4df8mw=='

stages:


- stage: JMeterTests
  displayName: JMeter Tests
  jobs:
  - job: JMeterTests
    displayName: JMeter Tests
    pool: myFinalPool
    steps: 

    - task: Bash@3
      displayName: Install Java
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          java -version

    - task: Bash@3
      displayName: Configure JMeter Memory
      inputs:
        targetType: 'inline'
        script: |
          echo "Setting JMeter memory options"
          echo 'export JVM_ARGS="-Xms512m -Xmx1024m"' >> ~/.bashrc
          source ~/.bashrc

    - task: Bash@3
      displayName: Install JMeter
      inputs:
        targetType: 'inline'
        script: |
          JMETER_VERSION=5.2.1
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xvzf apache-jmeter-$JMETER_VERSION.tgz
          sudo mv apache-jmeter-$JMETER_VERSION /opt/jmeter
          # Remove existing symbolic link if it exists
          if [ -L /usr/local/bin/jmeter ]; then
            sudo rm /usr/local/bin/jmeter
          fi
          sudo ln -s /opt/jmeter/bin/jmeter /usr/local/bin/jmeter
          jmeter -v


    - task: Bash@3
      displayName: EnduranceTest
      inputs:
        targetType: 'inline'
        script: 'jmeter -n -t automatedtesting/jmeter/EnduranceTestSuite.jmx -Jresdir=automatedtesting/jmeter/endurancepages.csv -l automatedtesting/jmeter/report/enduranceresults.jtl -e -o automatedtesting/jmeter/endurancereport'
    
    - task: Bash@3
      displayName: StressTest
      inputs:
        targetType: 'inline'
        script: |
          jmeter -n -t automatedtesting/jmeter/StressTestSuite.jmx -Jresdir=automatedtesting/jmeter/stresspages.csv -l automatedtesting/jmeter/report/stressresults.jtl -e -o automatedtesting/jmeter/stressreport

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'automatedtesting/jmeter'
        ArtifactName: 'jmeter'
        publishLocation: 'Container'
